name: Compile with Nuitka and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Download and Install Clang
      run: |
        Invoke-WebRequest -Uri https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe -OutFile llvm.zip
        Expand-Archive -Path llvm.zip -DestinationPath C:\llvm
        $env:Path += ";C:\llvm\bin"
      shell: powershell

    - name: Install PyTorch
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

    - name: Install other dependencies
      run: |
        pip install -r requirements.txt
        pip install nuitka

    - name: Compile with Nuitka
      run: |
        python -m nuitka --onefile --assume-yes-for-downloads --output-dir=dist main.py

    - name: Upload compiled artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-app
        path: dist/main.exe  # Adjust the path if necessary
